### PR TITLE
Fix MSVC compilation error

### PR DESCRIPTION
**Pull request by HolyWu**
The error only occurs when compiling for x86-32 though.

### CODE REVIEW

**Comment by dubhater** [comment]
Thanks. It is merged.

I'm curious: do you prefer plugins compiled with MSVC?

**Comment by HolyWu** [comment]
No, I'm quite fine with the binary compiled by gcc. Actuallty it's because the 32-bit DLL in your release crashes on Windows, therefore I just try to compile for debugging and happen to find the above problem then.

**Comment by dubhater** [comment]
Oh dear. Does it crash at an aligned load or store?

**Comment by dubhater** [comment]
Specifically, an aligned load or store from or to the stack?

**Comment by HolyWu** [comment]
I get this:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 10208.0x2c88]
sobel_u8_sse2 (
    srcp=0x6d297e0 "[[[[[[[Z\\[[Z\\\\\\\\Z\\[\\\\[\\[[\\[[\\\\\\[[\\\\[\\\\[[\\\\\\\\[[\\]]\\\\\\]]^]]__]]`_`_abaacaaaaa``ba``ab`_`_^_`^_]^^^^^]]\\\\]]", '\\' <repeats 11 times>, "[[\\[[Z\\\\[[\\\\ZZZ\\[[YZ[Y[[Z[[ZZ\\\\\\[[[Z[\\[[ZZ[\\][Z[[\\\\Z[[ZZ[[[\\[[[[[[[[Z\\[[[[\\\\\\Z[\\\\[[[Z"..., dstp=0xbb167c0 "",
    stride=1920, width=1920, height=1080, thresh=128) at sse2.cpp:57
57          __m128i th = _mm_set1_epi8(thresh);
(gdb)
```

**Comment by dubhater** [comment]
Yes, it's probably storing that on the stack. Say `set disassembly-flavor intel` and then `disassemble` until you see `=>` on the left. That's the instruction where it crashed.

The problem is that gcc's default stack alignment is only 4 bytes, instead of 16. (But only for 32 bit, it seems.) I have to pass `-mstackrealign` or use some `__attribute__` on the functions that use intrinsics.

**Comment by dubhater** [comment]
I replaced the win32 DLL.

**Comment by dubhater** [comment]
Do you remember what the error was?

**Comment by HolyWu** [comment]
`error C2719: 'x_limit_max': formal parameter with requested alignment of 16 won't be aligned`
The error repeats several times with different parameters.

**Comment by dubhater** [comment]
Thanks.

**Pull request closed without merging**
